### PR TITLE
:sparkles: Add support for google gemini model.

### LINKED ISSUE #304: Add support for Google Gemini models
We would like to add support for Google Gemini models.  This may be a more challenging 'good first issue' as to add this in will require some understanding of how Kai is interfacing with LLMs, yet the work is likely to be relatively easy.

For example, you can look at this PR to see how Amazon Bedrock was added to Kai:
https://github.com/konveyor/kai/pull/289/files

The work for adding a new model endpoint is to find an approach compatible with langchain, likely will mean adding a new package and small change to [kai/service/llm_interfacing/model_provider.py](https://github.com/konveyor/kai/blob/main/kai/service/llm_interfacing/model_provider.py) and [kai/config.toml](https://github.com/konveyor/kai/blob/main/kai/config.toml)

### PR DESCRIPTION
**Pull request by Myrausman**
Fixes #304

### CODE REVIEW

**Comment by jwmatthews** [comment]
@Myrausman thank you!

Quick look at the PR and looked great.  I'll help run through a manual test, but I don't expect to have time to help until Wednesday.

**Comment by fabianvf** [comment]
@Myrausman Would you be able to start the server in demo mode (DEMO_MODE=true), which should dump a bunch of cached responses into `kai/data/vcr/{app}/{model}`, then commit those files? That will let us run some verification on our end without needing to have a valid API key

**Comment by jwmatthews** [comment]
> I started server in demo mode but I'm not getting any cache new response for that particular model (pro-gemini).

@Myrausman did you run:
https://github.com/konveyor/kai/blob/main/example/run_demo.py

To get cached responses you need to send requests to the API, so that it can cache the response.
To send requests, easiest way is to use the run_demo.py against coolstore.

You can read this to learn more of how to run:
https://github.com/konveyor/kai/blob/main/example/README.md

**Review by jwmatthews — COMMENTED** [review]
Code changes look good...
Waiting on:
1) Update of cached responses
2) A maintainer to run a manual test to confirm working with Gemini

I am willing to test with a Gemini API key, I won't have time to help with that today, will try for helping tomorrow.

**Comment by jwmatthews** [comment]
@Myrausman this will help to give more context of updating cached responses

https://github.com/konveyor/kai/blob/main/docs/contrib/Demo_Mode.md#demo_mode-updating-cached-responses

**Comment by Myrausman** [comment]
followin this file [Contributing.md](https://github.com/konveyor/kai/blob/9bc5781e82478cedd46705d9f9486a8b132e8cbe/CONTRIBUTING.md ), when I'm running `make load-data` I am getting these error:
```
(.venv) myra@myra-ThinkPad-T14-Gen-2i:~/extra/lfx/kai$ make load-data
PYTHONPATH="/home/myra/extra/lfx/kai/kai:" python ./kai/service/incident_store/psql.py  --config_filepath ./kai/config.toml --drop_tables False
Console logging for 'kai' is set to level 'INFO'
File logging for 'kai' is set to level 'DEBUG' writing to file: '/home/myra/extra/lfx/kai/kai/service/incident_store/../../../logs/kai_psql.log'
INFO - 2024-08-22 02:58:32,264 - kai.service.kai_application.kai_application - [  kai_application.py:54   -             __init__()] - Tracing enabled.
modelid ############################### gemini-pro
INFO - 2024-08-22 02:58:32,281 - kai.service.kai_application.kai_application - [  kai_application.py:63   -             __init__()] - Selected provider: ChatGoogleGenerativeAI
INFO - 2024-08-22 02:58:32,282 - kai.service.kai_application.kai_application - [  kai_application.py:64   -             __init__()] - Selected model: gemini-pro
INFO - 2024-08-22 02:58:32,389 - kai.service.kai_application.kai_application - [  kai_application.py:84   -             __init__()] - Selected incident store: postgresql
INFO - 2024-08-22 02:58:32,460 - kai.service.incident_store.incident_store - [   incident_store.py:91   - load_reports_from_directory()] - Loading incident store with applications: ['ejb-security', 'ejb-remote', 'kitchensink', 'bmt', 'helloworld-mdb', 'cmt', 'greeter', 'tasks-qute', 'ticket-monster']

INFO - 2024-08-22 02:58:32,461 - kai.service.incident_store.incident_store - [   incident_store.py:95   - load_reports_from_directory()] - Loading application ejb-security

Traceback (most recent call last):
  File "/home/myra/extra/lfx/kai/./kai/service/incident_store/psql.py", line 4, in <module>
    cmd("postgresql")
  File "/home/myra/extra/lfx/kai/kai/service/incident_store/incident_store.py", line 475, in cmd
    load_reports_from_directory(incident_store, args.analysis_dir_path)
  File "/home/myra/extra/lfx/kai/kai/service/incident_store/incident_store.py", line 114, in load_reports_from_directory
    repo = Repo(repo_path)
           ^^^^^^^^^^^^^^^
  File "/home/myra/extra/lfx/kai/.venv/lib/python3.11/site-packages/git/repo/base.py", line 236, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/myra/extra/lfx/kai/samples/sample_repos/ejb-security
make: *** [Makefile:22: load-data] Error 1
```

**Comment by jwmatthews** [comment]
I think you just need to clone a few sample repos paths 

Look at this link and run the fetch_apps.py it mentions:

https://github.com/konveyor/kai/blob/main/docs/contrib/Dev_Environment.md#steps

**Comment by Myrausman** [comment]
After running `python3 run_demo.py`, I am getting the following output: [https://gist.github.com/Myrausman/3b9112e1342baa5a9accb8cb31d913d6](https://gist.github.com/Myrausman/3b9112e1342baa5a9accb8cb31d913d6).
 I also don't see any new files from the model in this location: `kai/data/vcr/{app}/{model}`.

**Review by jwmatthews — CHANGES_REQUESTED** [review]
The requirements.txt update looks incorrect.

@Myrausman did you run `pip-compile`, you should have more dependencies added to requirements.txt to account for the langchain-google-genai package and it's dependencies.

Let's update requirements.txt and then I think we'll be in shape to merge this.

I confirmed that when I ran pip-compile to update requirements.txt I had success running `run_example.py`.

I also confirmed that cached data is NOT being captured.  I am less sure of why that is happening.  

My thought is we move forward to merge this PR after the requirements.txt update is made, we accept we do not have cached data for gemini and work that as a separate issue, tracked as #315

**Comment by fabianvf** [comment]
interesting, I wonder if the google library is using a different library that isn't intercepted by VCR for managing the requests

**Comment by jwmatthews** [comment]
@Myrausman please take look at the merge conflicts we will need to resolve before we can merge.  We merged another PR yesterday that altered the requirements a little, so you will need to reexamine requirements.in, add your changes in, rerun pip-compile and test, then update this PR with the changes.

**Review by jwmatthews — APPROVED** [review]
LGTM

Ran and verified functional on Mac with arm64

**Comment by JonahSussman** [comment]
@Myrausman Thank you for your contribution!

**Pull request merged**
