### PR TITLE
:sparkles: Add Binary Build and Publish Workflow

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
This is not entirely ready yet:
- Ideally run a test to make sure the server is working.
- I would also like to fix up the name of the resultant zip files. Replace 'ubuntu' with 'linux' and remove the '-latest' part.

Otherwise an example of the published assets is here:
https://github.com/jmontleon/kai/releases/tag/v0.0.9

**Comment by jmontleon** [comment]
The zip filenames have been adjusted. I will follow up with a PR to add a test to sanity check the binaries.

**Comment by jmontleon** [comment]
- Added the architecture to the zip file name. 
- Also added Intel Mac builds.

**Comment by jmontleon** [comment]
Example of what will result: https://github.com/jmontleon/kai/releases/tag/v0.0.18

**Review by shawn-hurley — APPROVED** [review]

**Review by pranavgaikwad — APPROVED** [review]

**Pull request merged**
