### PR TITLE
:sparkles: Featre/analyzer task runner validator

### PR DESCRIPTION
**Pull request by shawn-hurley**
Just to get the initial code up there

### CODE REVIEW

**Comment by shawn-hurley** [comment]
This is looking correct, I think it can merge after fixing the conflicts

THings to note: 
* You need to have the kai-analyzer-rpc binary built and pass it in to code plan
* You need to have the rulesets on disk and pass them in to kai.

There seems to be intermintent errors in the pipe between kai-analyzer-prc and the client. I am looking into these things now, but I think having this in to start building off of for the parent child stuff and fixing a single incident may be worth it even with the issues. 

@fabianvf @JonahSussman @pranavgaikwad

**Review by pranavgaikwad — APPROVED** [review]
good PR, I like the re-structuring but at the same time, find the `agent` directory a bit awkward maybe something we could fix in the refactor. But overall makes sense to me.

**Comment by shawn-hurley** [comment]
I agree with you, but also it didn't feel like a task runner lol

**Comment by shawn-hurley** [comment]
We need to do a follow-up based on the above comments. 

Task Runners should not have the specifics of agents in their implementation. Instead they should be using one or more "agents". 

This moves us closer to making the "agents" LLM calls more composable. 

I think for us to do this, we need to have a good interface, between taking in strucuted data vs LLM Output.
s

**Review by fabianvf — APPROVED** [review]

**Review by JonahSussman — APPROVED** [review]
Agreed wrt "we need to have a good interface". LGTM for now

**Pull request merged**
